# Use a base image com Apache e PHP pré-instalados
FROM darthjee/tent-base:0.0.1
    
# Copie o código do projeto para o diretório padrão do Apache
COPY . /var/www/html

# Defina permissões para o diretório do Apache
RUN chown -R www-data:www-data /var/www/html

# Exponha a porta padrão do Apache
EXPOSE 80

# Inicie o Apache quando o container for iniciado
CMD ["apache2-foreground"]