# Use a base image from Dockerfile.tent-base
FROM darthjee/tent-base:0.0.1
    
# Copy the project code to the default Apache directory
COPY ./source/composer.json /home/app/app

RUN composer dump-autoload
